### PR TITLE
#163032301 Create meetup endpoint

### PR DESCRIPTION
**Pull request by wachiranduati**
**What does this PR do?**
This setsup the create meetup endpoint enabling a user to make post requests to create meetups via json requests.

**Description of Task to be completed?**
- create create meetup endpoint.

**How should this be manually tested?**
- git clone this repo 
> $ git clone https://github.com/wachiranduati/Questioner.git
- cd into it.
> $ cd Questioner
- switch into the develop branch
> $ git checkout develop
- Create a virtual enviroment
> $ virtualenv env
- Activate the virual environment
> $ source env/bin/activate
- Install the requirements by running
> $ pip install -r requirements.txt
- run pytest 
> $ pytest

**What are the relevant pivotal tracker stories?**
#163032301

Screenshots

screenshot_2019-01-09_01-06-25
screenshot_2019-01-09_01-07-45

### CODE REVIEW

**Comment by SolomonMacharia** [comment]
well written PR. Good to see your endpoints working.

**Comment by wachiranduati** [comment]
Thankyou @SolomonMacharia

**Comment by a-braham** [comment]
Nice to see all your tests pass..nice work

**Comment by wachiranduati** [comment]
Thanks @a-braham

**Pull request merged**
