### PR TITLE
#162972489 A user can create an account

### PR DESCRIPTION
**Pull request by wachiranduati**
**What does this PR do?**
The PR creates a `signup` html page so that users can signup to Questioner. In this PR the html content is written and styled using css. The Questioner logo is also introduced here with a couple of backdrops to enhance the aesthetics of the page.

**Description of Task to be completed?**
- Create the signup html page.
- Setup the signup form.
- Setup the username field in the signup form.
- Setup the email address field in the signup form.
- Setup the password field in the signup form.
- Setup the password confirmation field in the signup form.
- Setup the signup button in the signup form.
- Style the signup page.
- Make the signup page responsive

**How should this be manually tested?**
1. git clone this repo or download it into your local machine.
> $ git clone https://github.com/wachiranduati/Questioner.git
2. cd into the root folder of the repo
> $ cd Questioner
3. Open the signup.html page in your preferred browser

**What are the relevant pivotal tracker stories?**
#162972489

screen shot 2019-01-05 at 14 31 30
screen shot 2019-01-05 at 14 31 56
screenshots
screen shot 2019-01-05 at 14 31 18

### CODE REVIEW

**Comment by SolomonMacharia** [comment]
Great UI, well-detailed PR. Nice work.

**Comment by Ogollah** [comment]
Your background is making it hard for the user to get your message, on a small screen it is good but in a larger screen, we are missing your message.

**Comment by wachiranduati** [comment]
I will definitely create a bug story to remedy that...thanks for the review guys.

**Comment by Sulwe** [comment]
Good work, with modification about the background it will look better.

**Comment by wachiranduati** [comment]
Thanks @Sulwe I'm glad to say that I did change it by adding a darker overlay

**Pull request merged**
