### PR TITLE
#163124370 Update readme file to showcase all the working endpoints

### PR DESCRIPTION
**Pull request by wachiranduati**
**What does this PR do?**
It will update and recreate the readme file updating the previous endpoinsts table with the working ones described in the application. It will also reformat the data to include new fields and also do away with older ones.

**Description of Task to be completed?**
- Create a new endpoints table on the dillinger website
- Update the readme file with the proper information

**How should this be manually tested?**
- git clone this repo 
> $ git clone https://github.com/wachiranduati/Questioner.git
- cd into it.
> $ cd Questioner
- switch into the develop branch
> $ git checkout develop
- Navigate to the readme file at the root folder of the application and discover

**What are the relevant pivotal tracker stories?**
#163124370

### CODE REVIEW

**Comment by SolomonMacharia** [comment]
It's well written, Checked out your readme too. :100: :100:

**Comment by wachiranduati** [comment]
Thankyou very much @SolomonMacharia

**Comment by jackiegitari1234** [comment]
Awesome..am learning from you

**Comment by wachiranduati** [comment]
@jackiegitari1234 aaaaw....thankyou...

**Pull request merged**
